### ISSUE TITLE
Error: Execution context was destroyed, most likely because of a navigation.

### ISSUE THREAD

**Issue by narra-dev** [berstend/puppeteer-extra#173]
I tried to copy the guide. It all works fine, captcha is getting solved but then it crashes with a following error

<details><summary>Code snippet</summary>

```js
const puppeteer = require('puppeteer-extra')
 

const RecaptchaPlugin = require('puppeteer-extra-plugin-recaptcha')
puppeteer.use(
  RecaptchaPlugin({
    provider: {
      id: '2captcha',
      token: '069xxxxxxc6d' 
    },
    visualFeedback: true
  })
)
 

puppeteer.launch({ headless: true }).then(async browser => {
  const page = await browser.newPage()
  await page.goto('https://example.com')
  console.log('URL was opened');
 
  await page.solveRecaptchas()
  console.log('Captcha was solved');

  await Promise.all([
    page.waitForNavigation(),
    page.waitForSelector(),
    page.click(`#recaptcha-demo-submit`)
  ])
  await page.screenshot({ path: 'response.png', fullPage: true })
  await browser.close()
})
```
</details>

<details><summary>Full error log</summary>

```js
URL was opened
Captcha was solved
(node:6102) UnhandledPromiseRejectionWarning: Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (/Users/apple/Desktop/testingFiles2020/debug/node_modules/puppeteer/lib/ExecutionContext.js:167:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/apple/Desktop/testingFiles2020/debug/node_modules/puppeteer/lib/helper.js:111:15)
    at _documentPromise.executionContext.then (/Users/apple/Desktop/testingFiles2020/debug/node_modules/puppeteer/lib/DOMWorld.js:132:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/apple/Desktop/testingFiles2020/debug/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.click (/Users/apple/Desktop/testingFiles2020/debug/node_modules/puppeteer/lib/Page.js:1064:29)
    at puppeteer.launch.then (/Users/apple/Desktop/testingFiles2020/debug/app/captchaSolving.js:32:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:6102) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6102) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
</details>

I tried adding a `page.waitForSelector(),` line but it won't help.

**Comment by narra-dev** [comment]
Giving 5 seconds for page to load and adding and removing lines below helped me
```
    page.waitForSelector(),
    page.click(`#recaptcha-demo-submit`)
```
