### ISSUE TITLE
Could not find browser revision 737027

### ISSUE THREAD

**Issue by undrafted** [berstend/puppeteer-extra#192]
Hello, after following the basic installation on npm and just using `const puppeteer = require('puppeteer-extra')`, I'm getting the following error:

```
(node:41314) UnhandledPromiseRejectionWarning: Error: Could not find browser revision 737027. Run "npm install" or "yarn install" to download a browser binary.
    at ChromeLauncher.launch (x/node_modules/puppeteer-core/lib/Launcher.js:200:23)
    at async PuppeteerExtra.launch (x/node_modules/puppeteer-extra/dist/index.cjs.js:129:25)
    at async x/app.js:21:19
(node:41314) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:41314) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Version: "^3.1.9"

**Comment by Nerofox** [comment]
Waiting fix me too, pending the fix you can set manual path chrome.exe in option puppeteer
example on my windows : ./node_modules/puppeteer/.local-chromium/win64-737027/chrome-win/chrome.exe
`const chromeExecPath = "your url acces to chrome.exe"
        this.browser = await puppeteer.launch({
            (...)
            executablePath: chromeExecPath
        });`
Error is a bad resolve path on chrome executable

**Comment by adamculpepper** [comment]
@undrafted I was able to do a `npm update` and after Chromium updated my app started working again.
