### ISSUE TITLE
[Bug] "Invalid left-hand side in assignment"

### ISSUE THREAD

**Issue by avi12** [berstend/puppeteer-extra#438]
**Describe the bug**
I have the following TypeScript snippet:
```ts
import puppeteer from "puppeteer-extra";
import RecaptchaPlugin from "puppeteer-extra-recaptcha-plugin";

puppeteer.use(RecaptchaPlugin({
  provider: {
    id: "2captcha",
    token: "api-key"
  }
}));
```
When I try to run in development, it goes well
When I try to run in production, however:
```
PATH\dist\index.js:20891
__webpack_require__(71) = utils;
^

ReferenceError: Invalid left-hand side in assignment
    at Object.<anonymous> (PATH\dist\index.js:20891:1)
    at __webpack_require__ (PATH\dist\index.js:25:31)
    at Object.<anonymous> (PATH\dist\index.js:20625:13)
    at __webpack_require__ (PATH\dist\index.js:25:31)
    at Object.<anonymous> (PATH\dist\index.js:29149:13)
    at __webpack_require__ (PATH\dist\index.js:25:31)
    at Object.<anonymous> (PATH\dist\index.js:4032:15)
    at __webpack_require__ (PATH\dist\index.js:25:31)
    at Object.<anonymous> (PATH\dist\index.js:10555:28)
    at __webpack_require__ (PATH\dist\index.js:25:31)

```

**Versions**
`package.json`
```json
{
  "dependencies": {
    "puppeteer": "5",
    "puppeteer-extra": "^3.1.17",
    "puppeteer-extra-plugin-recaptcha": "^3.3.3"
  }
}
```

If it matters, I'm using [@vercel/ncc](https://www.npmjs.com/package/@vercel/ncc) to compile my code:
```powershell
ncc build src/index.ts -o dist -m
```

Regarding the `npx envinfo`, I couldn't run it in PowerShell, as I kept getting errors

**Comment by avi12** [comment]
After investigating, it seems like the [@vercel/ncc](https://www.npmjs.com/package/@vercel/ncc) tool was the issue
When I tried to compile using `tsc --build` and a `tsconfig.json`, I could run the compiled `dist/index.js`

**Comment by Thaske23** [comment]
wtf
