### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by timbojones86** [berstend/puppeteer-extra#492]
I get the following error:

TypeError: Cannot read property '1' of null
    at _getPlatformVersion (C:\Users\tim\Puppeteer_Test\node_modules\puppeteer-extra-plugin-stealth\evasions\user-agent-override\index.js:139:49)
    at Plugin.onPageCreated (C:\Users\tim\Puppeteer_Test\node_modules\puppeteer-extra-plugin-stealth\evasions\user-agent-override\index.js:161:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Plugin._onTargetCreated (C:\Users\tim\Puppeteer_Test\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:491:17)

Using Windows 32 Bit. Could this be the problem?

**Comment by prescience-data** [comment]
I'm assuming you are bundling this?

**Comment by berstend** [comment]
Not enough info, sorry. If you're interested in a solution to your problem please make a new issue and follow the Bug template.
