### ISSUE TITLE
[Bug] npm ERR! code ETARGET

### ISSUE THREAD

**Issue by xavruss** [berstend/puppeteer-extra#505]
to install get message :
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for automation-extra-plugin@^4.2.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
```

**Comment by fcpunk** [comment]
same issue

**Comment by MicrochipQ** [comment]
https://github.com/berstend/puppeteer-extra/issues/454

**Comment by zeglin** [comment]
Can't get pass that error as well. @MicrochipQ what's the workaround? #454 is quite a long thread.

```
npm install playwright playwright-extra @extra/humanize

npm ERR! code ETARGET
npm ERR! notarget No matching version found for automation-extra-plugin@^4.2.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by RafaelKuhn1212** [comment]
Use yarn

**Comment by Tavel** [comment]
> Use yarn

But it's the same issue with yarn:
```
yarn add @extra/humanize

➤ YN0000: ┌ Resolution step
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0001: │ Error: automation-extra-plugin@npm:^4.2.1: No candidates found
    at ge (C:\Users\Resource1\AppData\Local\node\corepack\yarn\3.4.1\yarn.js:439:7784)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 1)
    at async $s (C:\Users\Resource1\AppData\Local\node\corepack\yarn\3.4.1\yarn.js:390:10398)
➤ YN0000: └ Completed in 1s 444ms
➤ YN0000: Failed with errors in 1s 445ms
```
and after all packages upgrade:
```
yarn add @extra/humanize

➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: automation-extra-plugin@npm:^4.2.1: No candidates found
    at ge (C:\Users\Resource1\AppData\Local\node\corepack\yarn\3.4.1\yarn.js:439:7784)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 1)
    at async $s (C:\Users\Resource1\AppData\Local\node\corepack\yarn\3.4.1\yarn.js:390:10398)
➤ YN0000: └ Completed in 0s 777ms
➤ YN0000: Failed with errors in 0s 780ms
```

**Comment by Luen** [comment]
Seems like the package-lock is looking for version ^4.2.1
however, the version has a suffix 4.2.1**-next.587**
https://www.npmjs.com/package/automation-extra-plugin?activeTab=versions

**Comment by Tavel** [comment]
> > Use yarn
> 
> But it's the same issue with yarn:
> 
> ```
> yarn add @extra/humanize
> 
> ➤ YN0000: ┌ Resolution step
> ➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
> ➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
> ➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> ➤ YN0001: │ Error: automation-extra-plugin@npm:^4.2.1: No candidates found
>     at ge (C:\Users\Resource1\AppData\Local\node\corepack\yarn\3.4.1\yarn.js:439:7784)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Promise.allSettled (index 1)
>     at async $s (C:\Users\Resource1\AppData\Local\node\corepack\yarn\3.4.1\yarn.js:390:10398)
> ➤ YN0000: └ Completed in 1s 444ms
> ➤ YN0000: Failed with errors in 1s 445ms
> ```
> 
> and after all packages upgrade:
> 
> ```
> yarn add @extra/humanize
> 
> ➤ YN0000: ┌ Resolution step
> ➤ YN0001: │ Error: automation-extra-plugin@npm:^4.2.1: No candidates found
>     at ge (C:\Users\Resource1\AppData\Local\node\corepack\yarn\3.4.1\yarn.js:439:7784)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Promise.allSettled (index 1)
>     at async $s (C:\Users\Resource1\AppData\Local\node\corepack\yarn\3.4.1\yarn.js:390:10398)
> ➤ YN0000: └ Completed in 0s 777ms
> ➤ YN0000: Failed with errors in 0s 780ms
> ```

Actually I solved this by using this command:
```yarn add @extra/humanize@4.2.2-next.616```
