### ISSUE TITLE
plugin-user-data-dir: DeprecationWarning fs.rmdir

### ISSUE THREAD

**Issue by akornatskyy** [berstend/puppeteer-extra#516]
```sh
(node:27) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
    at emitRecursiveRmdirWarning (node:internal/fs/utils:790:13)
    at Object.rmdirSync (node:fs:1145:5)
    at Plugin.deleteUserDataDir (.../node_modules/puppeteer-extra-plugin-user-data-dir/index.js:72:11)
    at Plugin.onClose (.../node_modules/puppeteer-extra-plugin-user-data-dir/index.js:114:12)
```

**Comment by koteesy** [comment]
Yo. Did you find solution?

**Comment by akornatskyy** [comment]
Use `fs.rm(path, { recursive: true })` instead.

**Comment by thvd** [comment]
#502 should resolve it
