### ISSUE TITLE
[Bug] Popup window causes uncatchable error with 'puppeteer-extra-plugin-stealth'

### ISSUE THREAD

**Issue by markusenglund** [berstend/puppeteer-extra#541]
**Describe the bug**

When navigating to a website that creates a popup window (http://29ru.net), I get the following exception:
```
Error: Protocol error (Page.setLifecycleEventsEnabled): Target closed.
    at /home/markus/Desktop/bundle-analyzer/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:217:63
    at new Promise (<anonymous>)
    at CDPSession.send (/home/markus/Desktop/bundle-analyzer/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:216:16)
    at FrameManager.initialize (/home/markus/Desktop/bundle-analyzer/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:75:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Page._initialize (/home/markus/Desktop/bundle-analyzer/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:182:9)
    at async Function.create (/home/markus/Desktop/bundle-analyzer/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:176:9)
```

The problem goes away when I disable 'puppeteer-extra-plugin-stealth' or use the regular puppeteer package.

I used the following snippet to disable popups - this prevented the error from being thrown:
```
await page.evaluateOnNewDocument(() => {
   window.open = () => {};
});
```

You can also disable popups with `ignoreDefaultArgs: ["--disable-popup-blocking"]` but that only works when running Puppeteer with `headless: false`.

**Code Snippet**

```javascript
import puppeteer from "puppeteer-extra";
import StealthPlugin from "puppeteer-extra-plugin-stealth";
puppeteer.use(StealthPlugin());

(async () => {
  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    const response = await page.goto("http://29ru.net");
    await browser.close();
  } catch (err) {
    // NOTE: We never get here, the process just crashes.
    console.log("Error handler");
  }
})();
})()
```

**Versions**

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.23 GB / 15.40 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm

**Comment by berstend** [comment]
This should be fixed in #555 - please ping if that's not the case
