### ISSUE TITLE
[Bug] puppeteer-extra-plugin:user-data-dir.onClose called twice and causes Error. Also possible memory leak with Plugins

### ISSUE THREAD

**Issue by stupidpr** [berstend/puppeteer-extra#559]
**Describe the bug**

Running puppeteer extra with user-agent-plugin causes error "Error: ENOENT: no such file or directory, stat '/tmp/puppeteer_dev_profile-6fIz4i'" visible only in DEBUG mode. Look like "puppeteer-extra-plugin:user-data-dir.onClose"  called twice,

Run snippet with "DEBUG=puppeteer-extra,puppeteer-extra-plugin:* ./node_modules/.bin/ts-node ./test/script/double-close-crash.ts "

**Code Snippet**

```javascript
import {addExtra} from "puppeteer-extra";

let puppeteer = require('puppeteer');
puppeteer = addExtra(puppeteer);
const UserAgentOverride = require("puppeteer-extra-plugin-stealth/evasions/user-agent-override");
puppeteer.use(UserAgentOverride());

(async function main() {
	const browser = await puppeteer.launch({headless: true});
	console.log('Start');
	await browser.close();
	console.log('Done');
})();
```

Run: DEBUG=puppeteer-extra,puppeteer-extra-plugin:* ./node_modules/.bin/ts-node ./test/script/double-close-crash.ts 

```
 puppeteer-extra-plugin:base:stealth/evasions/user-agent-override Initialized. +0ms
  puppeteer-extra plugin registered stealth/evasions/user-agent-override +0ms
  puppeteer-extra dependencies missing Set(1) { 'user-preferences' } +1ms
  puppeteer-extra-plugin:base:user-preferences Initialized. +0ms
  puppeteer-extra plugin registered user-preferences +3ms
  puppeteer-extra dependencies missing Set(1) { 'user-data-dir' } +1ms
  puppeteer-extra-plugin:base:user-data-dir Initialized. +0ms
  puppeteer-extra-plugin:user-data-dir initialized {
  deleteTemporary: true,
  deleteExisting: false,
  files: [],
  folderPath: '/tmp',
  folderPrefix: 'puppeteer_dev_profile-'
} +0ms
  puppeteer-extra plugin registered user-data-dir +35ms
  puppeteer-extra orderPlugins:before [
  'stealth/evasions/user-agent-override',
  'user-preferences',
  'user-data-dir'
] +1ms
  puppeteer-extra orderPlugins:after [
  'stealth/evasions/user-agent-override',
  'user-preferences',
  'user-data-dir'
] +0ms
  puppeteer-extra-plugin:user-preferences _userPrefsFromPlugins { intl: { accept_languages: 'en-US,en' } } +0ms
  puppeteer-extra-plugin:user-data-dir created custom dir /tmp/puppeteer_dev_profile-6fIz4i +4ms
  puppeteer-extra-plugin:user-data-dir Wrote file /tmp/puppeteer_dev_profile-6fIz4i/Default/Preferences +6ms
Start
  puppeteer-extra-plugin:user-data-dir onClose +219ms
  puppeteer-extra-plugin:user-data-dir removeUserDataDir +0ms
(node:507333) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Done
  puppeteer-extra-plugin:user-data-dir onClose +28ms
  puppeteer-extra-plugin:user-data-dir removeUserDataDir +0ms
  puppeteer-extra-plugin:user-data-dir Error: ENOENT: no such file or directory, stat '/tmp/puppeteer_dev_profile-6fIz4i'
  puppeteer-extra-plugin:user-data-dir     at Object.statSync (node:fs:1536:3)
  puppeteer-extra-plugin:user-data-dir     at __node_internal_ (node:internal/fs/utils:793:8)
  puppeteer-extra-plugin:user-data-dir     at Object.rmdirSync (node:fs:1156:15)
  puppeteer-extra-plugin:user-data-dir     at Plugin.deleteUserDataDir (/var/www/projects/svb-bot/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:72:11)
  puppeteer-extra-plugin:user-data-dir     at Plugin.onClose (/var/www/projects/svb-bot/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:114:12)
  puppeteer-extra-plugin:user-data-dir     at process.emit (node:events:394:28)
  puppeteer-extra-plugin:user-data-dir     at process.emit (node:domain:475:12)
  puppeteer-extra-plugin:user-data-dir     at process.emit (/var/www/projects/svb-bot/node_modules/@cspotcode/source-map-support/source-map-support.js:527:35) +0ms
```

**Versions**

├── puppeteer-afp@1.0.1
├── puppeteer-extra-plugin-adblocker@2.11.11
├── puppeteer-extra-plugin-block-resources@2.2.9
├── puppeteer-extra-plugin-proxy@1.0.2
├── puppeteer-extra-plugin-stealth@2.7.8
├── puppeteer-extra@3.1.18
├── puppeteer@10.2.0

**Comment by stupidpr** [comment]
Also considering running in a row launch/close all the errors are reported at the end of whole script. It looks like they are accumulated during run and probably can be a reason of memory issues.

```
import {addExtra} from "puppeteer-extra";

let puppeteer = require('puppeteer');
puppeteer = addExtra(puppeteer);
const UserAgentOverride = require("puppeteer-extra-plugin-stealth/evasions/user-agent-override");
puppeteer.use(UserAgentOverride());

(async function main() {
	const browser = await puppeteer.launch({headless: true});
	console.log('Start');
	await browser.close();
	console.log('Done');

    const browser1 = await puppeteer.launch({headless: true});
    console.log('Start');
    await browser1.close();
    console.log('Done');

    const browser2 = await puppeteer.launch({headless: true});
    console.log('Start');
    await browser2.close();
    console.log('Done');
})();
```


```
  puppeteer-extra-plugin:base:stealth/evasions/user-agent-override Initialized. +0ms
  puppeteer-extra plugin registered stealth/evasions/user-agent-override +0ms
  puppeteer-extra dependencies missing Set(1) { 'user-preferences' } +1ms
  puppeteer-extra-plugin:base:user-preferences Initialized. +0ms
  puppeteer-extra plugin registered user-preferences +3ms
  puppeteer-extra dependencies missing Set(1) { 'user-data-dir' } +0ms
  puppeteer-extra-plugin:base:user-data-dir Initialized. +0ms
  puppeteer-extra-plugin:user-data-dir initialized {
  deleteTemporary: true,
  deleteExisting: false,
  files: [],
  folderPath: '/tmp',
  folderPrefix: 'puppeteer_dev_profile-'
} +0ms
  puppeteer-extra plugin registered user-data-dir +34ms
  puppeteer-extra orderPlugins:before [
  'stealth/evasions/user-agent-override',
  'user-preferences',
  'user-data-dir'
] +0ms
  puppeteer-extra orderPlugins:after [
  'stealth/evasions/user-agent-override',
  'user-preferences',
  'user-data-dir'
] +0ms
  puppeteer-extra-plugin:user-preferences _userPrefsFromPlugins { intl: { accept_languages: 'en-US,en' } } +0ms
  puppeteer-extra-plugin:user-data-dir created custom dir /tmp/puppeteer_dev_profile-e5bcz8 +4ms
  puppeteer-extra-plugin:user-data-dir Wrote file /tmp/puppeteer_dev_profile-e5bcz8/Default/Preferences +3ms
Start
  puppeteer-extra-plugin:user-data-dir onClose +244ms
  puppeteer-extra-plugin:user-data-dir removeUserDataDir +0ms
(node:507978) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Done
  puppeteer-extra no dependencies are missing +261ms
  puppeteer-extra orderPlugins:before [
  'stealth/evasions/user-agent-override',
  'user-preferences',
  'user-data-dir'
] +0ms
  puppeteer-extra orderPlugins:after [
  'stealth/evasions/user-agent-override',
  'user-preferences',
  'user-data-dir'
] +1ms
  puppeteer-extra-plugin:user-preferences _userPrefsFromPlugins { intl: { accept_languages: 'en-US,en' } } +0ms
  puppeteer-extra-plugin:user-data-dir created custom dir /tmp/puppeteer_dev_profile-srfUC8 +12ms
  puppeteer-extra-plugin:user-data-dir Wrote file /tmp/puppeteer_dev_profile-srfUC8/Default/Preferences +1ms
Start
  puppeteer-extra-plugin:user-data-dir onClose +196ms
  puppeteer-extra-plugin:user-data-dir removeUserDataDir +0ms
Done
  puppeteer-extra no dependencies are missing +221ms
  puppeteer-extra orderPlugins:before [
  'stealth/evasions/user-agent-override',
  'user-preferences',
  'user-data-dir'
] +0ms
  puppeteer-extra orderPlugins:after [
  'stealth/evasions/user-agent-override',
  'user-preferences',
  'user-data-dir'
] +1ms
  puppeteer-extra-plugin:user-preferences _userPrefsFromPlugins { intl: { accept_languages: 'en-US,en' } } +0ms
  puppeteer-extra-plugin:user-data-dir created custom dir /tmp/puppeteer_dev_profile-9jxKC7 +28ms
  puppeteer-extra-plugin:user-data-dir Wrote file /tmp/puppeteer_dev_profile-9jxKC7/Default/Preferences +4ms
Start
  puppeteer-extra-plugin:user-data-dir onClose +221ms
  puppeteer-extra-plugin:user-data-dir removeUserDataDir +0ms
Done
  puppeteer-extra-plugin:user-data-dir onClose +28ms
  puppeteer-extra-plugin:user-data-dir removeUserDataDir +0ms
  puppeteer-extra-plugin:user-data-dir Error: ENOENT: no such file or directory, stat '/tmp/puppeteer_dev_profile-9jxKC7'
  puppeteer-extra-plugin:user-data-dir     at Object.statSync (node:fs:1536:3)
  puppeteer-extra-plugin:user-data-dir     at __node_internal_ (node:internal/fs/utils:793:8)
  puppeteer-extra-plugin:user-data-dir     at Object.rmdirSync (node:fs:1156:15)
  puppeteer-extra-plugin:user-data-dir     at Plugin.deleteUserDataDir (/var/www/projects/svb-bot/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:72:11)
  puppeteer-extra-plugin:user-data-dir     at Plugin.onClose (/var/www/projects/svb-bot/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:114:12)
  puppeteer-extra-plugin:user-data-dir     at process.emit (node:events:406:35)
  puppeteer-extra-plugin:user-data-dir     at process.emit (node:domain:475:12)
  puppeteer-extra-plugin:user-data-dir     at process.emit (/var/www/projects/svb-bot/node_modules/@cspotcode/source-map-support/source-map-support.js:527:35) +0ms
  puppeteer-extra-plugin:user-data-dir onClose +6ms
  puppeteer-extra-plugin:user-data-dir removeUserDataDir +0ms
  puppeteer-extra-plugin:user-data-dir Error: ENOENT: no such file or directory, stat '/tmp/puppeteer_dev_profile-9jxKC7'
  puppeteer-extra-plugin:user-data-dir     at Object.statSync (node:fs:1536:3)
  puppeteer-extra-plugin:user-data-dir     at __node_internal_ (node:internal/fs/utils:793:8)
  puppeteer-extra-plugin:user-data-dir     at Object.rmdirSync (node:fs:1156:15)
  puppeteer-extra-plugin:user-data-dir     at Plugin.deleteUserDataDir (/var/www/projects/svb-bot/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:72:11)
  puppeteer-extra-plugin:user-data-dir     at Plugin.onClose (/var/www/projects/svb-bot/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:114:12)
  puppeteer-extra-plugin:user-data-dir     at process.emit (node:events:406:35)
  puppeteer-extra-plugin:user-data-dir     at process.emit (node:domain:475:12)
  puppeteer-extra-plugin:user-data-dir     at process.emit (/var/www/projects/svb-bot/node_modules/@cspotcode/source-map-support/source-map-support.js:527:35) +1ms
  puppeteer-extra-plugin:user-data-dir onClose +3ms
  puppeteer-extra-plugin:user-data-dir removeUserDataDir +0ms
  puppeteer-extra-plugin:user-data-dir Error: ENOENT: no such file or directory, stat '/tmp/puppeteer_dev_profile-9jxKC7'
  puppeteer-extra-plugin:user-data-dir     at Object.statSync (node:fs:1536:3)
  puppeteer-extra-plugin:user-data-dir     at __node_internal_ (node:internal/fs/utils:793:8)
  puppeteer-extra-plugin:user-data-dir     at Object.rmdirSync (node:fs:1156:15)
  puppeteer-extra-plugin:user-data-dir     at Plugin.deleteUserDataDir (/var/www/projects/svb-bot/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:72:11)
  puppeteer-extra-plugin:user-data-dir     at Plugin.onClose (/var/www/projects/svb-bot/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:114:12)
  puppeteer-extra-plugin:user-data-dir     at process.emit (node:events:406:35)
  puppeteer-extra-plugin:user-data-dir     at process.emit (node:domain:475:12)
  puppeteer-extra-plugin:user-data-dir     at process.emit (/var/www/projects/svb-bot/node_modules/@cspotcode/source-map-support/source-map-support.js:527:35) +0ms

```

**Comment by stupidpr** [comment]
Probably properProbably proper test case tht solves issue with same folder name. Main issue is still here

``` Javascript 
import {addExtra} from "puppeteer-extra";

const puppeteerCore = require('puppeteer');

async function runOne() {

    let puppeteer = addExtra(puppeteerCore);
    const UserAgentOverride = require("puppeteer-extra-plugin-stealth/evasions/user-agent-override");
    puppeteer.use(UserAgentOverride());

    const browser = await puppeteer.launch({headless: true} as any);
    console.log('Start');
    await browser.close();
    console.log('Done');
}
(async function main() {
    await runOne();
    await runOne();
    await runOne();
    await new Promise(resolve => setTimeout(resolve, 5000));
    console.log('DONE WAIT');
})();
```

**Comment by stupidpr** [comment]
Looks like because of PuppeteerExtraPlugin._bindBrowserEvents : 
```
[skipped]
 if (this.onClose) {
                process.on('exit', this.onClose.bind(this));
[skipped]
```
All the plugin instances with "onClose" are not released and cause memory leak in case of long run. Do I miss something?

**Comment by stupidpr** [comment]
> @stupidpr are you using the latest version of the plugin? we just switched from `onClose` to `onDisconnected` in #530

3.1.18. But in master I still see 

```
process.on('exit', this.onClose.bind(this))
```
That prevents proper release Plugins objects on browser close and keep them in memory until process end.

**Comment by berstend** [comment]
> I use 3.1.18.

I meant the plugins:
```
Successfully published:
 - puppeteer-extra-plugin-stealth@2.7.9
 - puppeteer-extra-plugin-user-data-dir@2.2.13
 - puppeteer-extra-plugin-user-preferences@2.2.13
 ```

`onClose` has been deprecated for a while, we could however add e.g. `if (this._hasChildClassMember('onClose')) { this.onClose() }`, then the event would only be registered when a plugin actually defines a `onClose` method.

In addition we could "debounce" the `onClose` event to only be emitted once per (browser-) session 🤔

**Comment by berstend** [comment]
But yeah, it seems like you're not using the latest stealth/user-data-dir plugin version, as `onClose` has been removed and we switched to `onDisconnected` which should not have these issues.

**Comment by stupidpr** [comment]
> 
> 
> But yeah, it seems like you're not using the latest stealth/user-data-dir plugin version, as `onClose` has been removed and we switched to `onDisconnected` which should not have these issues.

Yeah, I see what you mean now. Will try it  tomorrow. 
I wonder if continue supporting onClose in PuppeteerExtraPlugin makes sense as it still lead to hidden memory issue in any custom outdated Plugins

**Comment by stupidpr** [comment]
Confirm with latest issue was resolved

```
 - puppeteer-extra@3.1.18
 - puppeteer-extra-plugin-stealth@2.7.9
 - puppeteer-extra-plugin-user-data-dir@2.2.13
 - puppeteer-extra-plugin-user-preferences@2.2.13
```

**Comment by andrewcartwright1** [comment]
Hi,

I raised this on the discord - but my local appears to still be hanging at this point.

```
      } else {
        // Deprecated since node >= v14.14.0
        console.log('deleting profile');
        fs.rmdirSync(this._userDataDir, {
          recursive: true,
          maxRetries: 3
        })
        console.log('deleted profile');
      }
```

to mitigate this I have followed the advice here: https://github.com/berstend/puppeteer-extra/issues/421#issuecomment-773656458 which seems to work.

```
"puppeteer-extra-plugin-stealth":  "version": "2.9.0",
"puppeteer-extra-plugin-user-data-dir":  "version": "2.3.1",
"puppeteer-extra-plugin-user-preferences": "version": "2.3.1",
```
