### ISSUE TITLE
[Bug] Link down for firefox rv0.0.1

### ISSUE THREAD

**Issue by nogaruki** [berstend/puppeteer-extra#623]
**Describe the bug**
Hi ! 
While trying to install puppeteer-extra via NPM, I noticed that the link to download  [firefox rv0.0.1](https://github.com/puppeteer/juggler/releases/download/v0.0.1/firefox-win64.zip) is down. 
It is therefore impossible for me to finish the installation. 
Do you have any solution ? 

**Code Snippet**
```sh
ERROR: Failed to download Firefox rv0.0.1!
Error: Download failed: server returned code 404. URL: https://github.com/puppeteer/juggler/releases/download/v0.0.1/firefox-win64.zip
    at .\node_modules\puppeteer-extra\node_modules\puppeteer-firefox\lib\BrowserFetcher.js:264:21
    at ClientRequest.requestCallback (.\node_modules\puppeteer-firefox\lib\BrowserFetcher.js:320:7)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (.\node_modules\puppeteer-firefox\lib\helper.js:32:15)
    at Object.<anonymous> (.\node_modules\puppeteer-extra\node_modules\puppeteer-firefox\install.js:47:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**Versions**

  **System:**
- OS: Windows 10 10.0.19044
- CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
- Memory: 6.82 GB / 15.36 GB

  **Binaries:**
- Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
- Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
- npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD

  **npmPackages:**
- @types/debug: ^4.1.0 => 4.1.7
- @types/puppeteer: * => 5.4.5
- ava: ^2.4.0 => 2.4.0
- debug: ^4.1.1 => 4.3.3
- deepmerge: ^4.2.2 => 4.2.2
- documentation-markdown-themes: ^12.1.5 => 12.1.5
- npm-run-all: ^4.1.5 => 4.1.5
- puppeteer: 9 => 9.1.1
- puppeteer-extra-plugin: ^3.2.0 => 3.2.0
- puppeteer-extra-plugin-anonymize-ua: ^2.3.3 => 2.3.3
- rimraf: ^3.0.0 => 3.0.2
- rollup: ^1.27.5 => 1.32.1
- rollup-plugin-commonjs: ^10.1.0 => 10.1.0
- rollup-plugin-node-resolve: ^5.2.0 => 5.2.0
- rollup-plugin-sourcemaps: ^0.4.2 => 0.4.2
- rollup-plugin-typescript2: ^0.25.2 => 0.25.3
- ts-node: ^8.5.4 => 8.10.2
- tslint: ^5.20.1 => 5.20.1
- tslint-config-prettier: ^1.18.0 => 1.18.0
- tslint-config-standard: ^9.0.0 => 9.0.0
- typescript: 4.4.3 => 4.4.3

**Comment by UrielCh** [comment]
DUP #512
