### ISSUE TITLE
Support puppeteer v14

### ISSUE THREAD

**Issue by DustinJSilk** [berstend/puppeteer-extra#637]
Using puppeteer v14 with puppeteer-extra causes the browser to hang indefinitely after calling `browser.newPage()`

**Comment by andrei0x309** [comment]
I am using `^14.1.1` and I don't face this issue.

**Comment by carefulcomputer** [comment]
@DustinJSilk , i was getting error when I had pageinterception on.

`await page.setRequestInterception(true);`

with no code to intercept.
After I removed it, it started working. Check if you have same.

**Comment by Rongronggg9** [comment]
`puppeteer-extra-plugin-stealth` also makes jest exit with `ReferenceError`.

```
 PASS  test/utils/puppeteer.js (45.564 s)
  puppeteer
    ✓ puppeteer run (31544 ms)
    ✓ puppeteer without stealth (7136 ms)
    ✓ puppeteer with stealth (6539 ms)    <--- If skipped, everything will be fine

Running coverage on untested files...
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/utils/puppeteer.js.

      at node_modules/puppeteer/src/common/Debug.ts:58:8
      at debugLevel (node_modules/puppeteer/src/common/Debug.ts:58:8)
TypeError: (intermediate value).default is not a function
    at debugLevel (/media/rongrong/DATA/git-repo/RSSHub/node_modules/puppeteer/src/common/Debug.ts:58:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by berstend** [comment]
Puppeteer v14 support has just been improved, if this does not fix it please open a new issue.

```
Successfully published:
 - puppeteer-extra-plugin-adblocker@2.13.0
 - puppeteer-extra-plugin-anonymize-ua@2.4.0
 - puppeteer-extra-plugin-block-resources@2.4.0
 - puppeteer-extra-plugin-devtools@2.4.0
 - puppeteer-extra-plugin-recaptcha@3.6.0
 - puppeteer-extra-plugin-stealth@2.10.0
 - puppeteer-extra@3.3.0
 ```
