### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by aplesss** [berstend/puppeteer-extra#660]
When I use puppeteer-extra with puppeteer-extra-plugin-stealth in Electron app, The app run crash with error:
**Error: Cannot find module 'is-plain-object'**
    at webpackEmptyContext (*/.webpack/main/index.js:49950:10)
    at ./node_modules/merge-deep/node_modules/clone-deep/utils.js (*/.webpack/main/index.js:7736:88)
    at __webpack_require__ (/*/.webpack/main/index.js:53298:42)
    at ./node_modules/merge-deep/node_modules/clone-deep/index.js (/Users/hoangviet.nguyen/Documents/DevCode/Electron/termites-app/.webpack/main/index.js:7670:13)
    at __webpack_require__ (*/.webpack/main/index.js:53298:42)
    at ./node_modules/merge-deep/index.js (*/.webpack/main/index.js:7601:13)
    at __webpack_require__ (*/.webpack/main/index.js:53298:42)
    at */.webpack/main/index.js:9167:15)
    at __webpack_require__ (*/.webpack/main/index.js:53298:42)
    at ./node_modules/puppeteer-extra-plugin-stealth/index.js (*/.webpack/main/index.js:8967:34)

**Comment by SOUTHYYY** [comment]
Same error

**Comment by berstend** [comment]
I assume this should work: https://github.com/berstend/puppeteer-extra/issues/93#issuecomment-870173133

**Comment by megaacheyounes** [comment]
up
