### ISSUE TITLE
[Bug] [Firefox] An error occured while executing "onPageCreated" in plugin "stealth/evasions/user-agent-override": TypeError: Cannot read property 'userAgent' of undefined

### ISSUE THREAD

**Issue by meotimdihia** [berstend/puppeteer-extra#683]
**Describe the bug**
The bug happened on Firefox only. I tested on both Ubuntu and Windows.
```
An error occured while executing "onPageCreated" in plugin "stealth/evasions/user-agent-override": TypeError: Cannot read property 'userAgent' of undefined
    at Proxy.<anonymous> (c:\sources\a-cli\node_modules\playwright-extra\src\puppeteer-compatiblity-shim\index.ts:217:23)
    at runNextTicks (<node_internals>/internal/process/task_queues.js:60:5)
    at processImmediate (<node_internals>/internal/timers.js:437:9)
    at process.topLevelDomainCallback (<node_internals>/domain.js:152:15)
    at process.callbackTrampoline (<node_internals>/internal/async_hooks.js:128:24)
    at async Plugin.onPageCreated (c:\sources\a-cli\node_modules\puppeteer-extra-plugin-stealth\evasions\user-agent-override\index.js:69:8) {stack: 'TypeError: Cannot read property 'userAgent' o…h\evasions\user-agent-override\index.js:69:8)', message: 'Cannot read property 'userAgent' of undefined'}


```

```javascript
const { firefox } = require('playwright-extra')

import StealthPlugin from 'puppeteer-extra-plugin-stealth'

firefox.use(StealthPlugin())


chromium.launch({ headless: true }).then(async browser => {
  const page = await browser.newPage()

  console.log('Testing the stealth plugin..')
  await page.goto('https://bot.sannysoft.com', { waitUntil: 'networkidle' })
  await page.screenshot({ path: 'stealth.png', fullPage: true })

  console.log('All done, check the screenshot. ✨')
  await browser.close()
})
```

**Versions**

  Binaries:
    Node: 14.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\.yarn\bin\yarn.CMD
    npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD

    playwright: ^1.23.4 => 1.23.4
    playwright-extra: ^4.3.3 => 4.3.3
    puppeteer-extra-plugin-adblocker: ^2.13.4 => 2.13.4
    puppeteer-extra-plugin-stealth: ^2.11.0 => 2.11.0

**Comment by berstend** [comment]
Yup, I left that error noisy as to make it clear that Firefox + stealth doesn't make sense at the moment. :)

Firefox and Webkit don't support CDP which this evasion (and others need).

Most stealth evasions are expecting a Chromium based browser, so it doesn't make much sense to use the stealth plugin with it.

This has been explained in the readme though, therefore I'm closing this issue.
