### ISSUE TITLE
Not calling rimraf is path is missing 

### ISSUE THREAD

**Issue by jrejaud** [berstend/puppeteer-extra#720]
Today I used [patch-package](https://github.com/ds300/patch-package) to patch `puppeteer-extra-plugin-user-data-dir@2.4.0` for the project I'm working on.

I'm getting the following uncaught error in rimraf:

```
rimraf: missing path

at this function:
const rimraf = (p, options, cb) => {
  if (typeof options === 'function') {
    cb = options
    options = {}
  }
  assert(p, 'rimraf: missing path')
  assert.equal(typeof p, 'string', 'rimraf: path should be a string')
  assert.equal(typeof cb, 'function', 'rimraf: callback function required')
  assert(options, 'rimraf: invalid options argument provided')
  assert.equal(typeof options, 'object', 'rimraf: options should be object')
  defaults(options)
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/puppeteer-extra-plugin-user-data-dir/index.js b/node_modules/puppeteer-extra-plugin-user-data-dir/index.js
index a3711d8..d8f7ae1 100644
--- a/node_modules/puppeteer-extra-plugin-user-data-dir/index.js
+++ b/node_modules/puppeteer-extra-plugin-user-data-dir/index.js
@@ -66,6 +66,11 @@ class Plugin extends PuppeteerExtraPlugin {
   deleteUserDataDir() {
     debug('removeUserDataDir', this._userDataDir)
 
+    if (!this._userDataDir) {
+      console.warn('No userDataDir, not running rimraf')
+    }
+
+
     // We're using rimraf here because it throw errors and don't seem to freeze the process
     // If ressources busy or locked by chrome try again 4 times, then give up. overall a timout of 400ms
     rimraf(
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by MohamadKh75** [comment]
I'm facing this too:

```bash
rimraf: missing path
AssertionError [ERR_ASSERTION]: rimraf: missing path
    at rimraf (/home/X/node_modules/.pnpm/rimraf@3.0.2/node_modules/rimraf/rimraf.js:54:3)
    at Plugin.deleteUserDataDir (/home/X/node_modules/.pnpm/puppeteer-extra-plugin-user-data-dir@2.4.0_puppeteer-extra@3.3.4/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:71:5)
    at Plugin.onDisconnected (/home/X/node_modules/.pnpm/puppeteer-extra-plugin-user-data-dir@2.4.0_puppeteer-extra@3.3.4/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:118:12)
    at /home/X/node_modules/.pnpm/puppeteer-core@18.2.1/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:3:232
```

I don't have `puppeteer-extra-plugin-user-data-dir` 😐
I'm using:

```json
"puppeteer": "^18.2.1",
"puppeteer-extra": "^3.3.4",
"puppeteer-extra-plugin-stealth": "^2.11.1",
```

**Comment by MohamadKh75** [comment]
> Updated my comment to add a return statement (which would prevent the code from actually executing lol).
>
> @MohamadKh75 You are, check your modules:
>
> ```
>     at Plugin.deleteUserDataDir (/home/X/node_modules/.pnpm/puppeteer-extra-plugin-user-data-dir@2.4.0_puppeteer-extra@3.3.4/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:71:5)
> ```
>
> It's most likely being used as a dependency by puppeteer or a similar module.

I know it's being used! I meant it's not my direct dependency.

**Comment by ScottPierce** [comment]
I'm encountering this as well. Anyone know of a workaround?

**Comment by parampamosX** [comment]
I also faced this problem

**Comment by M1n007** [comment]
any info about this issue ?

**Comment by ScottPierce** [comment]
I created a PR for this - https://github.com/berstend/puppeteer-extra/pull/767

**Comment by ScottPierce** [comment]
Not sure what to expect though. It looks like this project isn't actively being maintained. That would also explain the lack of response. https://github.com/berstend/puppeteer-extra/pulse/monthly

**Comment by jrejaud** [comment]
You can patch it yourself on your local copy of the dependency (using patch-package like I did, for example). If you make a fork with your PR, you could put that on npm and let people use that as an alternative to this repo?

**Comment by ScottPierce** [comment]
I didn't know that `patch-package` was a thing - https://www.npmjs.com/package/patch-package

**Comment by JTJag** [comment]
Don't use this solution. I have not figured out why this error occurs, but if it is not handled it, into the directory with temporary files the browser directory remains. I used a new browser window to avoid the RAM leak problem and ran into an HDD memory leak. When creating a browser instance, pass userDataDir to browserParams. And don't forget to delete the directory after work

**Comment by berstend** [comment]
Fixed in #767 

```
Successfully published:
 - puppeteer-extra-plugin-user-data-dir@2.4.1
```
