### ISSUE TITLE
[Bug] executable path throws an error with puppeteer v19+

### ISSUE THREAD

**Issue by dukei** [berstend/puppeteer-extra#749]
**Describe the bug**

Steps to reproduce the problem:

Use puppeteer 19+ on windows
Try to call `puppeteer.executablePath()`
Expected result:
path to puppeteer executable

Actual result:
```
TypeError: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at join (node:path:429:7)
    at PuppeteerNode.get defaultDownloadPath [as defaultDownloadPath] (C:\SrcRep\asy-browser-service\node_modules\puppeteer-core\src\node\PuppeteerNode.ts:232:11)
    at ChromeLauncher.resolveExecutablePath (C:\SrcRep\asy-browser-service\node_modules\puppeteer-core\src\node\ProductLauncher.ts:105:28)
    at ChromeLauncher.executablePath (C:\SrcRep\asy-browser-service\node_modules\puppeteer-core\src\node\ChromeLauncher.ts:227:19)
    at PuppeteerNode.executablePath (C:\SrcRep\asy-browser-service\node_modules\puppeteer-core\src\node\PuppeteerNode.ts:213:27)
Puppeteer version v18 and below are unaffected
```
**Code Snippet**

```javascript
import puppeteer from "puppeteer-extra";
console.log(puppeteer.executablePath());
```

**Versions**
```
node v16.16.0
puppeteer v19.2.2
puppeteer-extra v3.3.4
```

**Comment by iamforrest** [comment]
same on Mac 

puppeteer v19.2.2
puppeteer-extra v3.3.4
node v18.10.0

**Comment by kw-pr** [comment]
See https://github.com/berstend/puppeteer-extra/issues/730
