### ISSUE TITLE
[Bug] ProtocolError: Network.getResponseBody timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

### ISSUE THREAD

**Issue by vgoklani** [berstend/puppeteer-extra#801]
Hey there,

I get this error and I'm not sure how to fix it (or even understand what it means). Please help, thanks!

```
ProtocolError: Network.getResponseBody timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at new Callback (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:61:35)
    at CallbackRegistry.create (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:106:26)
    at Connection._rawSend (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:26)
    at CDPSessionImpl.send (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:425:78)
    at next (/root/server/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:34:41)
    at CDPSessionImpl.send (/root/server/node_modules/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js:67:18)
    at /root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPResponse.js:99:100
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HTTPResponse.text (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/api/HTTPResponse.js:98:25)
    at async HTTPResponse.json (/root/server/node_modules/puppeteer-core/lib/cjs/puppeteer/api/HTTPResponse.js:110:25)
```

**Comment by braniubojni** [comment]
On my side I fix it by adding this key into launch object. U can adjust as match as u can

{
  // other props
  protocolTimeout: 1000 * 60 * 60, // an hour
}
