### ISSUE TITLE
[Bug] Puppeteer is missing. :-)

### ISSUE THREAD

**Issue by rehovicova** [berstend/puppeteer-extra#849]
It says puppeteer is missing, but puppeteer is installed. 

```
    Puppeteer is missing. :-)

    Note: puppeteer is a peer dependency of puppeteer-extra,
    which means you can install your own preferred version.

    - To get the latest stable version run: 'yarn add puppeteer' or 'npm i puppeteer'

    Alternatively:
    - To get puppeteer without the bundled Chromium browser install 'puppeteer-core'
    
Waiting for the debugger to disconnect...
/home/<user>/<project>/node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js:175
        static {
               ^

SyntaxError: Unexpected token '{'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/kristyna/work/tweet-scraper/node_modules/puppeteer-core/lib/cjs/puppeteer/api/api.js:35:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

Init:
```
const puppeteer = require('puppeteer-extra');
// add stealth plugin and use defaults (all evasion techniques)
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())
```

Dependencies:
```
"dependencies": {
    "puppeteer": "^21.4.0",
    "puppeteer-extra": "^3.3.6",
    "puppeteer-extra-plugin-stealth": "^2.11.2"
}
```

This produces the error above.

I have a different old project using puppeteer extra, so I copied the dependencies and this configuration works:

Dependencies:
```
"dependencies": {
    "puppeteer": "^18.2.1",
    "puppeteer-extra": "^3.3.4",
    "puppeteer-extra-plugin-stealth": "^2.11.1"
  }
  ```
Makes me think something is wrong with the versions I was trying to use. But
> #puppeteer-extra works with any puppeteer version:

Then I would expect to not have this error...

**Comment by pigeonmal** [comment]
Same error, in local that work fine, but in my hoster that throw this error

**Comment by Jimmylxue** [comment]
i have same error when it working in server platform

**Comment by electic** [comment]
I have the same issue. 

Update: Okay, I had to install Node 16 or higher. I had version 14 and if you have this version, it will not download the browsers. Installing 16 seems to have solved the problem.

**Comment by yo1nick** [comment]
Same problem but with playwright and node 20.10.0
 ⨯ Error: 

  I've tried loading "playwright-core", "playwright" - no luck.

  Make sure you install one of those packages or use the named 'addExtra' export,
  to patch a specific (and maybe non-standard) implementation of Playwright.

  To get the latest stable version of Playwright run:
  'yarn add playwright' or 'npm i playwright'

**Comment by tuquet** [comment]
i have same error with node 20+

**Comment by luiso1979** [comment]
same error here with node 20. Any updates?

I'm getting this error:

> Error: Cannot find module './module-test'
> Require stack:
> - /kft/resources/app/node_modules/@tootallnate/quickjs-emscripten/dist/index.js
> - /kft/resources/app/node_modules/pac-proxy-agent/dist/index.js
> - /kft/resources/app/node_modules/proxy-agent/dist/index.js
> - /kft/resources/app/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js
> - /kft/resources/app/node_modules/@puppeteer/browsers/lib/cjs/browser-data/chrome.js
> - /kft/resources/app/node_modules/@puppeteer/browsers/lib/cjs/browser-data/chrome-headless-shell.js
> - /kft/resources/app/node_modules/@puppeteer/browsers/lib/cjs/browser-data/browser-data.js
> - /kft/resources/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js
> - /kft/resources/app/node_modules/@puppeteer/browsers/lib/cjs/main.js
> - /kft/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js
> - /kft/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/node.js
> - /kft/resources/app/node_modules/puppeteer-core/lib/cjs/puppeteer/puppeteer-core.js
> - /kft/resources/app/node_modules/puppeteer-extra/dist/index.cjs.js
> - /kft/resources/app/dist/main/browser/chromeBrowser.js
> - /kft/resources/app/dist/main/browser/kftbrowser.js
> - /kft/resources/app/dist/main/main.js
> - 
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
>     at s._resolveFilename (node:electron/js2c/browser_init:2:114421)
>     at Module._load (node:internal/modules/cjs/loader:929:27)
>     at c._load (node:electron/js2c/node_init:2:13672)
>     at Module.require (node:internal/modules/cjs/loader:1150:19)
>     at require (node:internal/modules/cjs/helpers:119:18)
>     at Object.<anonymous> (/kft/resources/app/node_modules/@tootallnate/quickjs-emscripten/dist/index.js:44:14)
>     at Module._compile (node:internal/modules/cjs/loader:1271:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
>     at Module.load (node:internal/modules/cjs/loader:1126:32)

**Comment by pierreminiggio** [comment]
Same error here with node v20.18.0 and with these dependencies :
```json
{
    "puppeteer": "^23.6.0",
    "puppeteer-extra": "^3.3.6",
    "puppeteer-extra-plugin-stealth": "^2.11.2"
  }
  ```
  
Using the versions listed by @rehovicova :

```json
{
    "puppeteer": "^18.2.1",
    "puppeteer-extra": "^3.3.4",
    "puppeteer-extra-plugin-stealth": "^2.11.1"
  }
  ```
fixes it for me, but it's not a great solution because that older version of puppeteer is marked as a deprecated version.

Another solution would be welcome.

**Comment by sbaum2s** [comment]
> Same error here with node v20.18.0 and with these dependencies :
> 
> {
>     "puppeteer": "^23.6.0",
>     "puppeteer-extra": "^3.3.6",
>     "puppeteer-extra-plugin-stealth": "^2.11.2"
>   }
> Using the versions listed by [@rehovicova](https://github.com/rehovicova) :
> 
> {
>     "puppeteer": "^18.2.1",
>     "puppeteer-extra": "^3.3.4",
>     "puppeteer-extra-plugin-stealth": "^2.11.1"
>   }
> fixes it for me, but it's not a great solution because that older version of puppeteer is marked as a deprecated version.
> 
> Another solution would be welcome.

This fix works for me too
